version: '3'
services:
  pg:
    container_name: postgres_database
    image: postgres:latest
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: sequelize
